version: '3.8'

services:
  local_todo_postgres:
    image: postgres:14.5
    restart: always
    container_name: local_todo_postgres
    hostname: docker_compose_todo_local_psql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      TZ: ${TZ}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - data_todo_psql:/var/lib/postgresql/data

  local_todo_psql_admin:
    image: dpage/pgadmin4:6.14
    restart: always
    container_name: local_todo_psql_admin
    hostname: docker_compose_todo_local_psql_admin
    ports:
      - ${PGADMIN_DEFAULT_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - data_todo_admin:/var/lib/pgadmin
    depends_on:
      - local_todo_postgres

volumes:
  data_todo_psql:
  data_todo_admin:

